<?php

/**
 * @file
 * AWS Cloud module. This module handles UI interactions
 * with the cloud system for Amazon related clouds.  Amazon
 * clouds are EC2, OpenStack Nova, and Eucalyptus.
 *
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\aws_cloud\Aws\Ec2\KeyPairInterface;

/**
 * Implements hook_libraries_info()
 */
function aws_cloud_libraries_info() {
  return array(
    'awssdk' => array(
      'title' => 'AWS SDK for PHP',
      'vendor url' => 'http://aws.amazon.com/sdkforphp/',
      'download url' => 'http://aws.amazon.com/sdkforphp/',
      'version arguments' => array(
        'file' => 'sdk.class.php',
        'pattern' => "/define\('CFRUNTIME_VERSION', '(.*)'\);/",
        'lines' => 200,
      ),
      'files' => array(
        'php' => array(
          'sdk.class.php',
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_help()
 */
function aws_cloud_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.aws_cloud':
      $output = '<p>' . t('The aws_cloud module creates a user interface for managing AWS related clouds. AWS clouds are defined as EC2, OpenStack Nova, Cloudn and Eucalyptus.') . '</p>';

      return $output;
  }
}

/**
 * Set dynamic allowed values for the alignment field.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function aws_cloud_instance_type_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $instance_types = [];
  if ($entity->bundle() == 'aws_cloud') {
    $types = \Drupal::config('aws_cloud.settings')->get('aws_cloud_instance_types');
    $instance_array =  explode("\r\n", $types);
    foreach ($instance_array as $type) {
      $instance_types[$type] = $type;
    }
  }
  return $instance_types;
}

/**
 * Set dynamic allowed values for the alignment field.
 *
 * @param \Drupal\field\Entity\FieldStorageConfig $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\ContentEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function aws_cloud_availbility_zone_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {

  /* @var \Drupal\aws_cloud\Service\AwsEc2ServiceInterface $awsEc2Service */
  $awsEc2Service = \Drupal::service('aws_cloud.ec2');
  $availability_zones = [];

  if ($entity->bundle() == 'aws_cloud') {
    if ($entity->isNew()) {
      $route = \Drupal::routeMatch();
      $cloud_context = $route->getParameter('cloud_context');
    }
    else {
      $cloud_context = $entity->cloud_context();
    }
    $awsEc2Service->setCloudContext($cloud_context);
    $availability_zones = $awsEc2Service->getAvailabilityZones();
  }

  return $availability_zones;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function aws_cloud_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  // Add aws constraint to cloud_server_template.
  // This constraint will perform AWS specific validations
  $entity_types['cloud_server_template']->addConstraint('AWSConstraint');
}

/**
 * Implements hook_entity_view().
 */
function aws_cloud_entity_view(array &$build, \Drupal\aws_cloud\Aws\Ec2\KeyPairInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == 'aws_cloud_key_pair' && $view_mode == 'full') {
    // if the key is on the server, prompt user to download it
    if ($entity->getKeyFileLocation() != FALSE) {
      $url = \Drupal\Core\Url::fromRoute('entity.aws_cloud_key_pair.download', ['cloud_context' => $entity->cloud_context(), 'aws_cloud_key_pair' => $entity->id()])->toString();
      $messenger = \Drupal::messenger();
      $messenger->addWarning(t('<a href="@download_link">Download private key</a>.  Once downloaded, the key will be deleted from the server.',
        ['@download_link' => $url]
      ));
    }
  }
}

/**
 * Implementation of hook_cron().
 */
function aws_cloud_cron() {
  /* @var \Drupal\aws_cloud\Service\AwsEc2ServiceInterface $aws_ec2_service */
  $aws_ec2_service = \Drupal::service('aws_cloud.ec2');
  $clouds = \Drupal::entityQuery('cloud_context')->execute();
  foreach ($clouds as $cloud_id) {
    // update the following entities
    $aws_ec2_service->setCloudContext($cloud_id);
    $aws_ec2_service->updateInstances();
    $aws_ec2_service->updateSecurityGroups();
    $aws_ec2_service->updateKeyPairs();
    $aws_ec2_service->updateElasticIp();
    $aws_ec2_service->updateNetworkInterfaces();
    $aws_ec2_service->updateSnapshots();
    $aws_ec2_service->updateVolumes();

    // @todo: re-enabled instance bundling
  }

}
