cloud_server_template.cloud_server_template_type.*:
  type: config_entity
  label: 'Cloud Server Template type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
