<?php

/**
 * @file
 * Provides server template functionality for each cloud sub-system.
 * Works with Cloud module.
 *
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function cloud_server_template_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cloud_server_template module.
    case 'help.page.cloud_server_template':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Cloud Server Template') . '</p>';
      $output = '<p>' . t('The cloud_server_template module creates a user interface for users to manage clouds. Users can create server templates.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cloud_server_template_theme() {
  $theme = [];
  $theme['cloud_server_template'] = [
    'render element' => 'elements',
    'file' => 'cloud_server_template.page.inc',
    'template' => 'cloud_server_template',
  ];
  $theme['cloud_server_template_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'cloud_server_template.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_entity_operation().
 */
function cloud_server_template_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() == 'cloud_server_template' && $entity->hasLinkTemplate('launch')) {
    $operations['launch'] = [
      'title' => t('Launch'),
      'url' => $entity->toUrl('launch'),
      'weight' => 100,
    ];
  }
  return $operations;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function cloud_server_template_theme_suggestions_cloud_server_template(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#cloud_server_template'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'cloud_server_template__' . $sanitized_view_mode;
  $suggestions[] = 'cloud_server_template__' . $entity->bundle();
  $suggestions[] = 'cloud_server_template__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'cloud_server_template__' . $entity->id();
  $suggestions[] = 'cloud_server_template__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
