# Created by yas 2016/06/02

# Schema for the configuration files of the AWS Cloud module.
aws_cloud.settings:
  type: config_object
  label: 'AWS Cloud settings'
  mapping:
    aws_cloud_test_mode:
      type: boolean
      label: 'AWS Cloud Test Mode'